#!/usr/bin/env bash
# Deploy the full bitXtrade stack: frontend, backend, MongoDB, Redis.
# Usage:
#   ./scripts/deploy.sh              # local (default)
#   ./scripts/deploy.sh --local      # same
#   ./scripts/deploy.sh --production # production (needs deploy.env or env vars)
# Run from repository root.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

MODE="local"
if [[ "${1:-}" == "--production" ]] || [[ "${1:-}" == "-p" ]]; then
  MODE="production"
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()   { echo -e "${GREEN}[deploy]${NC} $*"; }
warn()  { echo -e "${YELLOW}[deploy]${NC} $*"; }
error() { echo -e "${RED}[deploy]${NC} $*"; exit 1; }

# --- Checks ---
command -v docker >/dev/null 2>&1 || error "Docker is not installed. Install Docker and try again."
docker info >/dev/null 2>&1 || error "Docker daemon is not running. Start Docker and try again."

if docker compose version >/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_CMD="docker-compose"
else
  error "Docker Compose is not installed. Install 'docker compose' or 'docker-compose' and try again."
fi

log "Using: $COMPOSE_CMD"

# --- Backend .env ---
if [[ ! -f backend/.env ]]; then
  if [[ -f backend/.env.example ]]; then
    warn "backend/.env not found. Copying from backend/.env.example"
    cp backend/.env.example backend/.env
    warn "Please edit backend/.env (JWT_SECRET, Firebase, etc.) and run this script again."
    exit 1
  else
    error "backend/.env not found and backend/.env.example is missing."
  fi
fi

# --- Production: load deploy.env and build override ---
COMPOSE_FILES="-f docker-compose.yml"
if [[ "$MODE" == "production" ]]; then
  DEPLOY_ENV="$REPO_ROOT/scripts/deploy.env"
  if [[ -f "$DEPLOY_ENV" ]]; then
    log "Sourcing $DEPLOY_ENV"
    set -a
    source "$DEPLOY_ENV"
    set +a
  fi

  # Required for production
  if [[ -z "${DEPLOY_DOMAIN:-}" ]]; then
    error "Production deploy requires DEPLOY_DOMAIN (e.g. yourdomain.com). Set it in scripts/deploy.env or environment."
  fi

  # Default API to api.$DEPLOY_DOMAIN
  API_DOMAIN="${API_DOMAIN:-api.$DEPLOY_DOMAIN}"
  FRONTEND_URL="https://${DEPLOY_DOMAIN}"
  API_URL="https://${API_DOMAIN}"
  WS_URL="wss://${API_DOMAIN}"
  ALLOWED_ORIGINS="${ALLOWED_ORIGINS:-https://$DEPLOY_DOMAIN,https://www.$DEPLOY_DOMAIN}"

  log "Production: Frontend=$FRONTEND_URL, API=$API_URL, ALLOWED_ORIGINS=$ALLOWED_ORIGINS"

  # Write docker-compose.prod.yml
  PROD_FILE="$REPO_ROOT/docker-compose.prod.yml"
  cat > "$PROD_FILE" << EOF
# Generated by scripts/deploy.sh --production
version: '3.8'

services:
  backend:
    env_file: ./backend/.env
    environment:
      PORT: "3000"
      NODE_ENV: production
      ALLOWED_ORIGINS: "$ALLOWED_ORIGINS"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: $API_URL
        NEXT_PUBLIC_WS_URL: $WS_URL
    environment:
      NEXT_PUBLIC_API_URL: $API_URL
      NEXT_PUBLIC_WS_URL: $WS_URL
EOF
  COMPOSE_FILES="$COMPOSE_FILES -f $PROD_FILE"
  log "Wrote $PROD_FILE"
fi

# --- Build and start ---
log "Building and starting stack (mode=$MODE)..."
if [[ "$MODE" == "production" ]]; then
  $COMPOSE_CMD $COMPOSE_FILES build --no-cache
else
  $COMPOSE_CMD $COMPOSE_FILES build
fi
$COMPOSE_CMD $COMPOSE_FILES up -d

# --- Wait for backend health ---
log "Waiting for backend to be healthy..."
BACKEND_URL="http://127.0.0.1:3001"
for i in {1..30}; do
  if curl -sf "$BACKEND_URL/health" >/dev/null 2>&1; then
    log "Backend is up at $BACKEND_URL"
    break
  fi
  if [[ $i -eq 30 ]]; then
    warn "Backend did not respond at $BACKEND_URL/health within 30s. Check: $COMPOSE_CMD $COMPOSE_FILES logs backend"
    break
  fi
  sleep 1
done

# --- Summary ---
echo ""
log "Deployment complete."
echo ""
echo "  Frontend:  http://localhost:3000"
echo "  Backend:   http://localhost:3001"
echo "  Health:    http://localhost:3001/health"
echo ""
if [[ "$MODE" == "production" ]]; then
  echo "  Production frontend URL: $FRONTEND_URL"
  echo "  Production API URL:      $API_URL"
  echo "  Put Nginx (or similar) in front and proxy to 127.0.0.1:3000 and 127.0.0.1:3001."
fi
echo ""
echo "  Logs:      $COMPOSE_CMD $COMPOSE_FILES logs -f"
echo "  Stop:      $COMPOSE_CMD $COMPOSE_FILES down"
echo ""
